# Generated by Django 2.2.3 on 2019-07-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=60)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('passWord', models.CharField(max_length=30, null=True)),
                ('userName', models.CharField(max_length=30, null=True)),
                ('phoneNumber', models.BigIntegerField(null=True)),
                ('jurisdiction', models.BooleanField(null=True)),
            ],
        ),
    ]
